/* Simulation code for Simple_car generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */
#if !defined(Simple_car__MODEL_H)
#define Simple_car__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Simple_car_functions.h"


extern void Simple_car_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Simple_car_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Simple_car_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Simple_car_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Simple_car_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Simple_car_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Simple_car_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Simple_car_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Simple_car_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Simple_car_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Simple_car_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Simple_car_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Simple_car_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Simple_car_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Simple_car_relationDescription(int i);
extern void Simple_car_function_initSample(DATA *data, threadData_t *threadData);
extern int Simple_car_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Simple_car_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple_car_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple_car_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple_car_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple_car_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Simple_car_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Simple_car_linear_model_frame(void);
extern const char* Simple_car_linear_model_datarecovery_frame(void);
extern int Simple_car_mayer(DATA* data, modelica_real** res, short *);
extern int Simple_car_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Simple_car_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Simple_car_setInputData(DATA *data, const modelica_boolean file);
extern int Simple_car_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Simple_car_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Simple_car_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int Simple_car_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void Simple_car_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void Simple_car_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Simple_car_inputNames(DATA* data, char ** names);
extern int Simple_car_dataReconciliationInputNames(DATA* data, char ** names);
extern int Simple_car_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Simple_car_functionLocalKnownVars(DATA*, threadData_t*);
extern int Simple_car_symbolicInlineSystem(DATA*, threadData_t*);

#include "Simple_car_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Simple_car__MODEL_H) */


