/* Additional record code for LeadCar generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "LeadCar_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

