/* Simulation code for LeadCar generated by the OpenModelica Compiler OpenModelica 1.17.0~5-gb8b118d. */
#if !defined(LeadCar__MODEL_H)
#define LeadCar__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "LeadCar_functions.h"


extern void LeadCar_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void LeadCar_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int LeadCar_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int LeadCar_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int LeadCar_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int LeadCar_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int LeadCar_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int LeadCar_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int LeadCar_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int LeadCar_checkForAsserts(DATA *data, threadData_t *threadData);
extern int LeadCar_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int LeadCar_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int LeadCar_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* LeadCar_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* LeadCar_relationDescription(int i);
extern void LeadCar_function_initSample(DATA *data, threadData_t *threadData);
extern int LeadCar_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int LeadCar_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LeadCar_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LeadCar_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LeadCar_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LeadCar_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int LeadCar_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* LeadCar_linear_model_frame(void);
extern const char* LeadCar_linear_model_datarecovery_frame(void);
extern int LeadCar_mayer(DATA* data, modelica_real** res, short *);
extern int LeadCar_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int LeadCar_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int LeadCar_setInputData(DATA *data, const modelica_boolean file);
extern int LeadCar_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void LeadCar_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void LeadCar_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int LeadCar_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void LeadCar_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void LeadCar_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int LeadCar_inputNames(DATA* data, char ** names);
extern int LeadCar_dataReconciliationInputNames(DATA* data, char ** names);
extern int LeadCar_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int LeadCar_functionLocalKnownVars(DATA*, threadData_t*);
extern int LeadCar_symbolicInlineSystem(DATA*, threadData_t*);

#include "LeadCar_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(LeadCar__MODEL_H) */


